export enum TipoEvento {
  INICIALIZACAO = 'INICIALIZACAO',
  MANUTENCAO = 'MANUTENCAO',
  ANOMALIA = 'ANOMALIA',
  FALHA = 'FALHA',
  RECUPERACAO = 'RECUPERACAO',
  ATUALIZACAO = 'ATUALIZACAO',
}