export enum TipoSensor {
  TEMPERATURA = 'TEMPERATURA',
  PRESSAO = 'PRESSAO',
  RADIACAO = 'RADIACAO',
  OXIGENIO = 'OXIGENIO',
  VELOCIDADE = 'VELOCIDADE',
  COMBUSTIVEL = 'COMBUSTIVEL',
  ELETRICO = 'ELETRICO',
  COMPUTACIONAL = 'COMPUTACIONAL',
}